CTRL-22717:QSPI driver dependency/compile issue
Initial QSPI driver back ported had the orginal changes
sent for review to open source community without any local
modifications but it had small compilation error and
iProc architecture dependency in kConfig was missing.

So in this patch,

1. Fixed a compilation error related to CONFIG_SLEEP
2. Added dependency ARCH_BCM_IPROC to use driver for
   all SoC's based on iProc architecture.

BUG:CTRL-22717
Change-Id: Ide1d27b4a4d8ba7d7c8afdd25a03027b8f699a6c
Reviewed-on: http://gerrit-ccxsw.rtp.broadcom.com:8080/27491
Reviewed-by: vpx_checkpatch status <vpx_checkpatch@broadcom.com>
Tested-by: RAVEENDRA PADASALAGI <raveendra.padasalagi@broadcom.com>
Reviewed-by: Vikram Prakash <vikram.prakash@broadcom.com>
Tested-by: vpx_autobuild status <vpx_autobuild@broadcom.com>
Tested-by: vpx_smoketest status <vpx_smoketest@broadcom.com>
Reviewed-by: Scott Branden <scott.branden@broadcom.com>