VOIP-6539 sound: soc: cygnus: add depends on HAS_DMA
add depends on HAS_DMA to Kconfig.  This fixes error reported
by kbuild test robot when building for ARCH=m32r:
ERROR: "bad_dma_ops" [sound/soc/bcm/snd-soc-cygnus.ko] undefined!

Bug: VOIP-6539
Change-Id: I8f4b2daf5a3c6e6f60e5b48d142105988199eaca
Reviewed-on: http://gerrit-ccxsw.rtp.broadcom.com:8080/30786
Reviewed-by: vpx_checkpatch status <vpx_checkpatch@broadcom.com>
Tested-by: vpx_autobuild status <vpx_autobuild@broadcom.com>
Tested-by: vpx_smoketest status <vpx_smoketest@broadcom.com>
Reviewed-by: Scott Branden <scott.branden@broadcom.com>